version: "3.8"
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: creation_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    # needs below, bacause .env file's setting isn't loaded in multi-stage build Dockerfile.
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRED_IN: ${JWT_EXPIRED_IN}
      JWT_MAXAGE: ${JWT_MAXAGE}
    networks:
      - creation_network
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: creation_mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "6500:3306"
    volumes:
      - creation_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - creation_network

  kv_store:
    image: redis:latest
    container_name: creation_redis
    networks:
      - creation_network

volumes:
  creation_db:

networks:
  creation_network: