[package]
name = "creation-adapter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
creation-service = { path = "../creation-service" }
sqlx.workspace = true
serde.workspace = true